server:
  port: 8080
  servlet:
    context-path: /

spring:
  servlet:
    multipart:
      max-file-size: 2049MB     # 设置单文件大小 2G
      max-request-size: 5121MB  # 设置总上传数据总大小 5G
  redis:
    host: 127.0.0.1
    port: 6379
    password:        # 密码,默认密码为空
    database: 0      # Redis数据库索引（默认为0）,如果设置为1，那么存入的key-value都存放在select 1中
    max-wait: 30000  # 连接池最大阻塞等待时间（使用负值表示没有限制）
    max-active: 100  # 连接池最大连接数（使用负值表示没有限制）
    max-idle: 20     # 连接池中的最大空闲连接
    min-idle: 0      # 连接池中的最小空闲连接
    timeout: 5000    # 连接超时

jetcache:
  # 统计间隔，0表示不统计，开启后定期在控制台输出缓存信息
  statIntervalMinutes: 15
  # 是否把cacheName作为远程缓存key前缀
  areaInCacheName: false
  # 本地配置 local
  local:
    default:
      type: linkedhashmap     # other choose：caffeine
      keyConvertor: fastjson2 # other choose：fastjson/jackson
      limit: 100
  # 远程配置 redis
  remote:
    default:
      type: redis.lettuce   # other choose：redis/redis.lettuce/redisson
      uri: redis://127.0.0.1:6379/0 # redis://密码@IP:端口/库 , 若密码是带非法字符的，需要URL编码
      database: 9
      keyConvertor: fastjson2 # other choose：fastjson/jackson
      broadcastChannel: projectA
      valueEncoder: java # other choose：kryo/kryo5
      valueDecoder: java # other choose：kryo/kryo5
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50