
server:
  port: 8082 # tomcat端口
  servlet:
    context-path: /springboot-test-remote # 服务名称
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 5120MB # 5G上传单个最大文件
      max-request-size: 10240MB  # 10G 多文件上传最大
  server_url:
    get_url_userdto: http://localhost:8080/springboot-test-remoteservice/rest/v1/get/userdto
    get_url_userdto2: http://localhost:8080/springboot-test-remoteservice/rest/v1/get/userdto2
    get_url_userdtolist: http://localhost:8080/springboot-test-remoteservice/rest/v1/get/userdtolsit
    post_url_userdto: http://localhost:8080/springboot-test-remoteservice/rest/v1/post/userdto
    post_url_userdto2: http://localhost:8080/springboot-test-remoteservice/rest/v1/post/userdto2
    post_url_userdto3: http://localhost:8080/springboot-test-remoteservice/rest/v1/post/userdto3
    put_url_userdto: http://localhost:8080/springboot-test-remoteservice/rest/v1/put/userdto
    put_url_userdto2: http://localhost:8080/springboot-test-remoteservice/rest/v1/put/userdto2
    delete_url_userdto: http://localhost:8080/springboot-test-remoteservice/rest/v1/delete/userdto
    delete_url_userdto2: http://localhost:8080/springboot-test-remoteservice/rest/v1/delete/userdto2
  web_url:
    file_url_getFileInfo: http://192.168.2.42:8084/springboot-test-file/file/split/v1/getFileInfo
    file_url_downloadSplitFile: http://192.168.2.42:8084/springboot-test-file/file/split/v1/downloadLocalFile
    file_url_getFileInfo2: http://localhost:8080/dgp-dubbo-server-web/rest/ommb/v1/getFileInfo
    file_url_downloadSplitFile2: http://localhost:8080/dgp-dubbo-server-web/rest/ommb/v2/offlinepackage/downloadSplitFile

remote:
  url:
    file_upload: http://localhost:8080/springboot-test-remoteservice/rest/file/post/upload/v1   # 上传单文件
    file_upload1: http://localhost:8080/springboot-test-remoteservice/rest/file/post/upload/v2  # 上传单文件，并且带参数
    file_upload2: http://localhost:8080/springboot-test-remoteservice/rest/file/post/upload/v3  # 上传多文件

dist:
  rest-api:
    package-scan: com.dist.server.rest
  rest:
    url:
      remoteservice: http://localhost:8080/springboot-test-remoteservice/rest/v1

# 远程服务调用地址
feign:
  telihui:
    enable: true  # 是否启用 第三方特力惠 登录验证
    url: http://10.18.130.240/   # 第三方-特力惠

debug: false




