# 主配置文件主要用来存放公共设置，不受环境配置影响
server:
  port: 8080
  servlet:
    context-path: /springboot-test-yml

spring:
  profiles:
    active: dev # 此处由maven的环境选择决定
  web:
    isopenurl: true # 是否要启动时打开浏览器
    googleexcute: explorer  # 本地浏览器地址
    loginurl: http://localhost:${server.port}/${server.servlet.context-path}/swagger-ui.html  # 要打开的网址

# 动态修改
isOne: true

dynamicvalue:
  data: asd
  value: 123
