server:
  port: 19001  # https port
  http:
    port: 19000  # http port
  ssl:
    key-store: classpath:client.p12
    key-store-password: 12345678
    keyStoreType: PKCS12
    key-alias: client

spring:
  servlet:
    multipart:
      max-file-size: 2049MB  # 设置单个文件大小 2G
      max-request-size: 5121MB  # 设置总上传数据总大小 5G

# Swagger UI 地址
# http://localhost:19000/swagger-ui/index.html#/
