# 主配置文件主要用来存放公共设置，不受环境配置影响
server:
  port: 8080
  servlet:
    context-path: /springboot-test-jdbc

# 项目启动自动打开swagger页面
swagger:
  isopenurl: true # 是否要启动时打开浏览器
  googleexcute: explorer  # 本地浏览器地址
  loginurl: http://localhost:${server.port}/${server.servlet.context-path}/swagger-ui.html  # 要打开的网址

# spring 配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: test
    password: pass
    driver-class-name: com.mysql.jdbc.Driver
  jmx:
    default-domain: springboot
ds:
  maxActive: 200
  initialSize: 10
  minIdle: 10
  maxWait: 60000
  testWhileIdle: true
  removeAbandoned: true
  removeAbandonedTimeout: 180
  logAbandoned: false
  minEvictableIdleTimeMillis: 60000
  timeBetweenEvictionRunsMillis: 60000
  testOnBorrow: false
  validationQuery: select 1 from dual
  poolPreparedStatements: true
  maxPoolPreparedStatementPerConnectionSize: 200
  monitor: false # 是否启用数据库连接池监控，开启后损失部分性能
  driverClass: ${spring.datasource.driver-class-name}
  url: ${spring.datasource.url}
  username: ${spring.datasource.username}
  password: ${spring.datasource.password}