# yml 映射单个属性、数组、list、map、list<map>，List<User>，User等
my-attributes:
  # 单个值
  value: 345
  # 数组
  valueArray: 1,2,3,4,5,6,7,8,9
  # list
  valueList:
    - 13579
    - 246810
  # map
  valueMap:
    name: 张三
    age: 20
    sex: female
  # list<map>
  valueMapList:
    - name: 李四
      age: 21
    - name: caven
      age: 31
  valueUserList:
    - name: 李四
      age: 24
    - name: 张三
      age: 22
  valueUser:
    name: 安其拉
    age: 18

system:
  name: 一个博客系统
  user:
    username: 李四
    password: pass123
    roleObjectList:
      - roleId: 1
        roleName: 省级角色
      - roleId: 2
        roleName: 市级角色
    authorityList:
      - 上传
      - 下载
    friendArray: 张三、王强

unions:
  partI:
    name: 李四
  partII:
    age: 19

jasypt:
  encryptor:
    # 必须设置，加密的密钥，自定义即可，为了安全 password属性不推荐存储在属性文件中，而应作为系统属性、命令行参数或环境变量传递。
    password: 34ui23de34h
    # 加解密算法，默认 PBEWithMD5AndDES，是 md5 加 des 标准加密
    algorithm: PBEWithMD5AndDES
    # bean名称，默认 jasyptStringEncryptor，可以使用自定义加密
    bean: jasyptStringEncryptor
    property:
      #默认 ENC(密文内容)
      prefix: ENC(
      suffix: )

jasyptTest: ENC(z9/xqdfLNLz1SU4DId7XCw==)