server:
  port: 8080
  servlet:
    context-path: /@project.artifactId@
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: test
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource  # 默 com.zaxxer.hikari.HikariDataSource 数据库连接池类型
  flyway:
    enabled: true         # 默 true，启用flyway,首次会自动创建 flyway_schema_history 表
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#    url: jdbc:postgresql://localhost:5433/test
    user: test
    password: pass
    ## 以下都是默认配置[可选的]
    table: flyway_schema_history        # 默 flyway_schema_history，用于记录所有的版本变化记录
#    table: flyway_user_history        # 默 flyway_schema_history，用于记录所有的版本变化记录
    check-location: true                # 默 true，校验 locations 路径下必须存在 *.sql文件
    locations:                          # 默 classpath:db/migration，用于扫描的迁移脚本目录
      - classpath:db/migration          # 默 classpath:db/migration，sql脚本文件位置
#      - classpath:db/user               # 默 classpath:db/migration，sql脚本文件位置
    baseline-on-migrate: true          # 默 false，若发现schema数据库非空时，当存在flyway_schema_history表，会执行sql文件，不存在，则不执行sql文件并启动时抛出异常
    baseline-version: 1                 # 默 1，开始执行基准迁移时对现有的schema的版本打标签
    sql-migration-prefix: V             # 默 V，SQL迁移的文件名前缀
    repeatable-sql-migration-prefix: R  # 默 R，可重复 SQL迁移的文件名前缀
    sql-migration-separator: __         # 默 __，版本__描述.sql 的分隔符
    sql-migration-suffixes: .sql        # 默 .sql，SQL 迁移的文件名后缀
    init-sqls:    # 默空，当初始化好连接时要执行的SQL
