# 主配置文件主要用来存放公共设置，不受环境配置影响
server:
  port: 8080
  servlet:
    context-path: /springboot-test-redis2
spring:
  redis:
    database: 6   # Redis数据库索引（默认为0）
    host: 127.0.0.1  # Redis服务器地址
    port: 6379         # Redis服务器连接端口
    password:    # Redis服务器连接密码（默认为空）
    max-wait: 30000    # 连接池最大阻塞等待时间（使用负值表示没有限制）
    max-active: 100   # 连接池最大连接数（使用负值表示没有限制）
    max-idle: 20     # 连接池中的最大空闲连接
    min-idle: 0     # 连接池中的最小空闲连接
    timeout: 5000  # 连接超时时间（毫秒）
  #自定义配置
  redis2:
    database: 5   # Redis数据库索引（默认为0）
    host: 127.0.0.1  # Redis服务器地址,这里用其它redis所在服务器的ip地址
    port: 6379         # Redis服务器连接端口
    password:    # Redis服务器连接密码（默认为空）
    timeout: 5000  # 连接超时时间（毫秒）