server:
  port: 8280
  servlet:
    context-path: rocketmq

rocketmq:
  name-server: http://127.0.0.1:9876
  producer:
    group: rocketmq_test_group   # 发送者组
    send-message-timeout: 3000   # 消息发送超时毫秒数
#  consumer:
#    group: rocketmq_test_group
#    topic:
