server:
  port: 8080
  servlet:
  servlet.context-path: /springboot-test-shptools
spring:
  jpa:
    show-sql: true # 是否在控制台打印SQL语句
    properties:
      hibernate:
        default_schema: dgpnr_pro
  aop:
    auto: true
    proxy-target-class: true # 默认设置为false,使用的是标准Java动态代理的实现（接口），而不是cglib（类）
  jmx:
    default-domain: dgpbms # 指定JMX define name
  datasource:
    sql-script-encoding: utf-8 # 解决中文乱码
    username: dgpnr_pro
    password: nr#2019
    url: jdbc:oracle:thin:@52.82.99.12:15213/ORCL # @localhost/ORCL  #
    driver-class-name: oracle.jdbc.driver.OracleDriver
ds:
  maxActive: 200
  initialSize: 10
  minIdle: 10
  maxWait: 60000
  testWhileIdle: true
  removeAbandoned: true
  removeAbandonedTimeout: 180
  logAbandoned: false
  minEvictableIdleTimeMillis: 60000
  timeBetweenEvictionRunsMillis: 60000
  testOnBorrow: false
  validationQuery: select 1 from dual
  poolPreparedStatements: true
  maxPoolPreparedStatementPerConnectionSize: 200
  monitor: false # 是否启用数据库连接池监控，开启后损失部分性能
  driverClass: ${spring.datasource.driver-class-name}
  url: ${spring.datasource.url}
  username: ${spring.datasource.username}
  password: ${spring.datasource.password}

#在application.properties文件中引入日志配置文件
#=====================================  log  =============================
logging:
  config: classpath:logback-boot.xml

