# 流程测试
tangram:
  server_url: http://192.168.122.13:8231/tangram/
  example1: # 示例 1  常规流程1
    process_id: 6260ef3978aa846f08fbqwes  # 流程id
  example2: # 示例 2  常规流程2
    process_id: 6260ef3978aa846f08fbqwes  # 流程id
  brwg:     # 包容网关
    process_id: 6260ef3978aa846f08fbqwes  # 流程id  抽象 AbstractTangram
  gwzx:     # 规委在线
    process_id: 6260ef3978aa846f08fbqwes  # 流程id