server:
  port: 8080
  servlet:
    context-path: /springboot-remote-web-19000
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 2049MB # 设置单文件大小 2G
      max-request-size: 5121MB # 设置总上传数据总大小 5G
