server:
  port: 8080
  servlet:
    context-path: /
spring:
  servlet:
    multipart:
      max-file-size: 2049MB     # 设置单文件大小 2G
      max-request-size: 5121MB  # 设置总上传数据总大小 5G

source:
  fileStorageLocation: D://FileTest//文件存储位置
  fileFragmentationLocation: D://FileTest//文件分片位置
  fileCompositePosition: D://FileTest//文件合成位置
rest:
  resource: /rest/public/resource

cors:
  allow: false # 是否允许跨域请求
  mapping: "/**" # 限定的跨域资源
  method: "*" # 允许的跨域请求方式，* 需要以单引号'
  origin: "*" # 允许的请求域