server:
  port: 8080
  servlet:
    context-path: /@project.artifactId@
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: test
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource  # 默 com.zaxxer.hikari.HikariDataSource 数据库连接池类型
  liquibase:
    enabled: true   # 默true 启用
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    #url: jdbc:postgresql://localhost:5433/test
    user: test
    password: pass
    ## 以下都是默认配置[可选的]
    change-log: classpath:/db/db.changelog-master.yaml  # 默 classpath:/db/changelog/db.changelog-master.yaml，变更日志
#    change-log: classpath:db/changelog/V1.0.0.sql  # 默 classpath:/db/changelog/db.changelog-master.yaml，变更日志
    database-change-log-table: DATABASECHANGELOG                  # 默 DATABASECHANGELOG，数据库更改日志表
    database-change-log-lock-table: DATABASECHANGELOGLOCK         # 默 DATABASECHANGELOGLOCK，数据库更改日志锁定表
