server:
  port: 8082
  servlet:
    context-path: /springboot-test-file
spring:
 servlet:
   multipart:
     enabled: true
     max-file-size: 500MB # 上传单个最大文件
     max-request-size: 1000MB  # 多文件上传最大

source:
  fileStorageLocation: D://FileTest//文件存储位置
  fileFragmentationLocation: D://FileTest//文件分片位置
  fileCompositePosition: D://FileTest//文件合成位置
rest:
  resource: /rest/public/resource

cors:
  allow: false # 是否允许跨域请求
  mapping: "/**" # 限定的跨域资源
  method: "*" # 允许的跨域请求方式，* 需要以单引号'
  origin: "*" # 允许的请求域