server:
  port: 8080
  servlet:
    context-path: /springboot-test-file
spring:
 servlet:
   multipart:
     enabled: true
     max-file-size: 200MB # 上传单个最大文件
     max-request-size: 1000MB  # 多文件上传最大

source:
  fileStorageLocation: D://FileTest//文件存储位置
  fileFragmentationLocation: D://FileTest//文件分片位置
  fileCompositePosition: D://FileTest//文件合成位置
rest:
  resource: /rest/public/resource