
xxl:
  job:
    admin:
      addresses: http://192.168.159.136:8080/xxl-job-admin/
    accessToken: default_token
    executor:
      appname: xxl-job-executor-sample
      address:
      ip:
      port: 9991
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
