# dev 配置
spring:
  # 数据库连接配置
  datasource:
    url: jdbc:mysql://localhost:3306/duke?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: duke     # 用户：duke/pass  权限库：duke
    password: EklGbpXO+Msj65L02gb2XxGskxybn5i6nUmVDwh49pKIBJlsOuqAEB4safeSldUpuIjlExB7COR8fgUU9QYNPQ==
    driver-class-name: com.mysql.jdbc.Driver
  # spring data jpa 配置
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      # ddl-auto: update
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database: mysql
    show-sql: true
  jmx:
    default-domain: dubboTest

# 数据库连接池参数配置
ds:
  maxActive: 200
  initialSize: 10
  minIdle: 10
  maxWait: 60000
  testWhileIdle: true
  removeAbandoned: true
  removeAbandonedTimeout: 180
  logAbandoned: false
  minEvictableIdleTimeMillis: 60000
  timeBetweenEvictionRunsMillis: 60000
  testOnBorrow: false
  validationQuery: select 1 from dual
  poolPreparedStatements: true
  maxPoolPreparedStatementPerConnectionSize: 200
  monitor: false # 是否启用数据库连接池监控，开启后损失部分性能
  driverClass: ${spring.datasource.driver-class-name}
  url: ${spring.datasource.url}
  username: ${spring.datasource.username}
  password: ${spring.datasource.password}
  #filters: config
  # 与加密的密码相同，用于解密使用
  connectionProperties: password=EklGbpXO+Msj65L02gb2XxGskxybn5i6nUmVDwh49pKIBJlsOuqAEB4safeSldUpuIjlExB7COR8fgUU9QYNPQ==

# dubbo 配置
dubbo:
  application:
    name: provider
  registry:
    protocol: dubbo  #dubbo/zookeeper 协议
    #address: 127.0.0.1:2182  # zookeeper协议配置方式
    address: zookeeper://127.0.0.1:2181  # dubbo协议配置方式
    #address: zookeeper://127.0.0.1:2183?backup=127.0.0.1:2184,127.0.0.1:2185  # dubbo协议配置集群-zk主从配置方法
    #address: 127.0.0.1:2183,127.0.0.1:2184,127.0.0.1:2185  # zookeeper协议配置集群-zk非主从配置方法
  protocol:
    port: 30103
  annotation:
    package: com.dist.server
  provider:
    version: 1.0.0 #dubbo默认版本号，在url显示为default.version=xxx

# 项目启动是否启动执行sql文件 true/false ,建议首次创建后false关闭，避免数据丢失!
jdbc:
  isStartSql: true

debug: false